# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0002_auto_20170812_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
