# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0003_auto_20170812_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeeAsk.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeeAsk.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('answers', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeeAsk.User')),
            ],
        ),
    ]
