# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0007_auto_20170829_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
