# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0008_auto_20170830_1855'),
    ]
