# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0009_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answers',
            field=models.IntegerField(default=0),
        ),
    ]
