# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0010_auto_20170905_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeeAsk.Post'),
        ),
    ]
