# Generated by Django 2.0 on 2017-12-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeeAsk', '0012_auto_20170917_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
